name: CI

on: [pull_request, push]

jobs:
  typescript:
    name: TypeScript
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm ci

    - run: npm audit || { sleep 10 && npm audit; } || { sleep 30 && npm audit; }
      if: runner.os == 'Linux'

    - run: npm run lint

    - run: npm run package --scripts-prepend-node-path
